FROM ubuntu:16.04
MAINTAINER Suresh Kanniappan <Suresh.Kanniappan@verizon.com>

# ENV http_proxy http://x.x.x.x:8080
# ENV https_proxy http://x.x.x.x:8080

RUN apt-get -y update && apt-get -y install tree && apt-get -y install vim
