---

- name: Install Nginx server in ubuntu
  apt: name=nginx state=present update_cache=yes
  when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" )

- name: Install epel-release package in CentOS Server
  yum: name=epel-release update_cache=yes state=latest
  when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )

#- name: Update packages in CentOS Server
#  yum: name=* state=latest
#  when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )

- name: Install Nginx server in CentOS
  yum: name=nginx update_cache=yes state=present
  when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )

...
