- name: Demonstrates the STOP of provisioned Docker Container through Ansible playbook
  hosts: localhost
  tasks:
   - name: Stop Ubuntu Docker Container
     docker_container:
        name: "ubuntu{{item}}"
        state: stopped
     with_sequence: start=1 end=2 
   
   - name: Stop CentOS Docker Container
     docker_container:
        name: "centos{{item}}"
        state: stopped
     with_sequence: start=1 end=2 

